-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'REGISTRATION_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'REGISTRATION_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'RESERVATION_MODIFIED';
